-- AlterTable
ALTER TABLE `UserProfile` ADD COLUMN `height` DOUBLE NULL,
    ADD COLUMN `primaryGoal` ENUM('MUSCLE_GAIN', 'STRENGTH', 'WEIGHT_LOSS', 'GENERAL_FITNESS') NOT NULL DEFAULT 'MUSCLE_GAIN',
    ADD COLUMN `weight` DOUBLE NULL;
